from pathlib import Path
import html,json

CSS='''@import url("https://fonts.googleapis.com/css2?family=DM+Mono&family=Source+Serif+4:wght@400;600;700&display=swap");:root{--ink:#25221e;--paper:#faf8f3;--sand:#eee8dc;--line:#d7cdbd;--clay:#b95f42;--moss:#55705d;--muted:#746d63}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.55 "Source Serif 4",Georgia,serif}.wrap{max-width:1220px;margin:auto;padding:48px 24px 80px}.eyebrow,.mono,button,.chip,input{font-family:"DM Mono",monospace}.eyebrow{color:var(--clay);letter-spacing:.1em;font-size:11px;text-transform:uppercase}.hero{display:flex;justify-content:space-between;gap:24px;border-bottom:1px solid var(--line);padding-bottom:30px}.hero h1{font-size:clamp(42px,7vw,76px);line-height:.9;margin:12px 0}.hero p{max-width:560px;color:var(--muted);font-size:18px}.stamp{height:max-content;background:var(--ink);color:#fff;padding:10px 13px;font-size:11px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:28px 0}.metric{border:1px solid var(--line);padding:18px;background:#fff}.metric b{display:block;font:34px/1 "DM Mono",monospace}.metric span{color:var(--muted);font-size:12px}.notice{border-left:4px solid var(--clay);background:#f3eadc;padding:14px 17px;margin:22px 0;color:#594134}.section{margin-top:42px}.section h2{font-size:28px;margin:0 0 10px}.tools{display:flex;gap:8px;flex-wrap:wrap}.chip,button{border:1px solid var(--line);background:#fff;padding:7px 10px;font-size:11px;cursor:pointer;color:var(--ink)}.chip.active,.chip:hover,button:hover{background:var(--ink);color:#fff}.toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:18px 0}.toolbar input{min-width:240px;flex:1;border:1px solid var(--line);padding:9px;background:#fff}.finding{display:grid;grid-template-columns:62px 130px 100px 1fr 30px;gap:12px;align-items:start;border-top:1px solid var(--line);padding:15px 4px}.score{font:600 23px/1 "DM Mono",monospace;color:var(--clay)}.state{font:11px "DM Mono",monospace;color:var(--moss);text-transform:uppercase}.family{font:11px "DM Mono",monospace}.url{overflow-wrap:anywhere}.detail{grid-column:4/6;display:none;background:var(--sand);padding:12px 14px;font-size:14px}.finding.open .detail{display:block}.more{border:0;background:none;padding:0;font-size:20px}.chain{display:grid;grid-template-columns:90px 130px 1fr;gap:12px;border-top:1px solid var(--line);padding:13px 4px}.chain b{font-family:"DM Mono",monospace}.links{display:flex;gap:10px;flex-wrap:wrap}.links a{color:var(--clay);font:12px "DM Mono",monospace}@media(max-width:700px){.hero{display:block}.stamp{display:inline-block}.metrics{grid-template-columns:repeat(2,1fr)}.finding{grid-template-columns:54px 1fr 24px}.finding .state,.finding .family,.finding .url{grid-column:2}.detail{grid-column:2/4}.chain{grid-template-columns:70px 1fr}.chain div:last-child{grid-column:2}}'''

def write_html(path,summary,evidence,chains):
 esc=lambda x:html.escape(str(x)); data=json.dumps(evidence).replace('</','<\\/')
 cards=[('URLs',summary.get('urls',0)),('Signals',len(evidence)),('Corroborated',sum('corroborated' in str(x.get('status','')) for x in evidence)),('Chains',len(chains))]
 metrics=''.join(f'<div class="metric"><b>{esc(v)}</b><span>{esc(k)}</span></div>' for k,v in cards)
 families=sorted({str(x.get('family','OTHER')) for x in evidence}); filters=''.join(f'<button class="chip" data-family="{esc(f)}">{esc(f)}</button>' for f in families)
 rows=[]
 for e in evidence[:200]:
  gates=''.join(f'<li>{esc(x)}</li>' for x in e.get('evidence_gate',[])); controls=''.join(f'<li>{esc(x)}</li>' for x in e.get('negative_controls',[])); tools=' '.join(esc(t) for t in e.get('tools',[])); search=esc(' '.join(map(str,[e.get('family',''),e.get('url',''),e.get('status',''),tools])).lower())
  rows.append(f'<article class="finding" data-family="{esc(e.get("family","OTHER"))}" data-search="{search}"><div class="score">{int(e.get("confidence_score",0)):02}</div><div class="state">{esc(e.get("status","lead"))}</div><div class="family">{esc(e.get("family","OTHER"))}</div><div class="url">{esc(e.get("url",""))}<br><span class="mono">{tools}</span></div><button class="more" aria-label="show evidence" onclick="this.parentElement.classList.toggle(\'open\')">+</button><div class="detail"><b>Evidence gates</b><ul>{gates or "<li>Manual validation required</li>"}</ul><b>Negative controls</b><ul>{controls or "<li>Fresh baseline</li>"}</ul></div></article>')
 chain_rows=''.join(f'<div class="chain"><b>{int(c.get("score",0)):02}</b><span class="mono">{esc(c.get("id",""))}</span><div><b>{esc(c.get("title",""))}</b><br><span class="mono">{esc(c.get("host",""))} · {esc(", ".join(c.get("signals",[])))}</span></div></div>' for c in chains[:100])
 page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RiftHound research report</title><style>{CSS}</style></head><body><main class="wrap"><header class="hero"><div><div class="eyebrow">Authorized research report</div><h1>RiftHound<br>Field Notes</h1><p>Signals are organized for verification, not inflated into claims. Expand a row to see the evidence gate and the control that should disprove it.</p></div><div class="stamp">PRESET {esc(summary.get("preset","balanced")).upper()}<br>AUTHOR {esc(summary.get("author",""))}</div></header><section class="metrics">{metrics}</section><aside class="notice"><b>Interpretation boundary.</b> Scores rank investigation priority; they are not CVSS. Catalog, scanner, and pattern matches remain leads until their stated evidence gates are met.</aside><section class="section"><div class="eyebrow">Artifacts</div><div class="links"><a href="evidence-ledger.json">Evidence ledger</a><a href="chain-hypotheses.json">Chain hypotheses</a><a href="summary.json">Run summary</a><a href="artifacts/">Raw artifacts</a></div></section><section class="section"><div class="eyebrow">Evidence ledger</div><h2>What deserves a closer look</h2><div class="toolbar"><input id="search" placeholder="Filter by family, URL, state, or tool"><button id="all" class="chip active">All signals</button>{filters}<button onclick="copyHandoff()">Copy handoff</button></div><div id="findings">{''.join(rows) or '<p>No evidence signals were recorded.</p>'}</div></section><section class="section"><div class="eyebrow">Correlation</div><h2>Chain hypotheses</h2>{chain_rows or '<p>No multi-signal chains were generated.</p>'}</section></main><script>const report={data};let family='';const search=document.querySelector('#search');function filter(){{const q=search.value.toLowerCase();document.querySelectorAll('.finding').forEach(r=>r.hidden=(family&&r.dataset.family!==family)||!r.dataset.search.includes(q))}}document.querySelectorAll('[data-family]').forEach(b=>b.onclick=()=>{{family=b.dataset.family;document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter()}});document.querySelector('#all').onclick=()=>{{family='';document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));document.querySelector('#all').classList.add('active');filter()}};search.oninput=filter;function copyHandoff(){{const visible=report.filter(x=>!family||x.family===family).slice(0,20).map(x=>`- [${{x.confidence_score}}] ${{x.family}} ${{x.url}} (${{x.status}})`).join('\\n');navigator.clipboard.writeText(`RiftHound handoff\\n${{visible}}`);alert('Visible evidence copied as a handoff.')}}window.loadRiftHoundReport=(next)=>{{report.splice(0,report.length,...next);filter()}};</script></body></html>'''
 Path(path).write_text(page)

def write_markdown(path,summary,evidence,chains):
 l=['# RiftHound research report','',f"URLs: **{summary.get('urls',0)}** · Signals: **{len(evidence)}** · Chains: **{len(chains)}**",'', '> Scores are investigation priority, not CVSS. Every lead needs its stated evidence gate.','', '## Evidence']
 for e in evidence[:50]:l += [f"### {e.get('confidence_score',0):03} — {e.get('family')} — {e.get('status')}",f"`{e.get('url','')}`",f"Tools: {', '.join(e.get('tools',[]))}",'']
 l+=['## Chain hypotheses','']
 for c in chains[:60]:l += [f"### {c.get('score',0):03} — {c.get('id')} — {c.get('title')}",f"Host: `{c.get('host')}`",'']
 Path(path).write_text('\n'.join(l)+'\n')
