PHASES={1:'Recon & Asset Discovery',2:'Browser/Input Discovery',3:'Validation & Exploitation Proof',4:'Evidence, Chains & Reporting'}
TITLES={
1:'Read program scope and policy',2:'Normalize authorized roots',3:'Enumerate passive subdomains',4:'Enrich with Amass',5:'Probe live HTTP services',6:'Fingerprint technologies/CDNs',7:'Crawl application URLs',8:'Collect historical URLs',9:'Reduce/normalize URL corpus',10:'Collect JavaScript assets',11:'Collect source maps',12:'Discover security.txt/OpenAPI',13:'Map authentication pages',14:'Map OAuth/OIDC discovery',15:'Map GraphQL/API endpoints',16:'Map WebSocket/realtime endpoints',17:'Map third-party integrations',18:'Record cache/security headers',19:'Discover parameters',20:'Build host/surface inventory',
21:'Locate message receivers',22:'Locate postMessage senders',23:'Validate event.origin checks',24:'Validate event.source checks',25:'Review wildcard targetOrigin',26:'Review origin substring/regex checks',27:'Review null/opaque origins',28:'Review popup/opener relationships',29:'Review parent/frame relationships',30:'Review recipient navigation',31:'Review message schemas',32:'Review MessageChannel/MessagePort',33:'Review BroadcastChannel',34:'Review window.name persistence',35:'Review extension/native bridges',36:'Trace DOM sources to sinks',37:'Isolate reflected parameters',38:'Classify reflection context',39:'Check raw/decoded metacharacters',40:'Review service workers',41:'Review Trusted Types/CSP',42:'Review COOP/COEP/CORP',43:'Review WebAuthn/passkeys',44:'Review deep/custom links',45:'Run negative-control matrix',
46:'Map token/session storage',47:'Inspect cookie flags',48:'Inventory OAuth authorize flow',49:'Verify PKCE use',50:'Verify state binding',51:'Verify nonce binding',52:'Verify exact redirect URI',53:'Review callback open redirects',54:'Review OAuth web_message delivery',55:'Review account linking',56:'Review login CSRF',57:'Review session invalidation',58:'Review password reset lifecycle',59:'Review MFA recovery lifecycle',60:'Review tenant invitations',61:'Build two-account test matrix',62:'Review BOLA/IDOR reads',63:'Review BOLA/IDOR writes',64:'Review BOPLA/mass assignment',65:'Review BFLA/function auth',66:'Review API version skew',67:'Review GraphQL resolver auth',68:'Review persisted GraphQL queries',69:'Review gRPC-Web methods',70:'Review JSON-RPC methods',71:'Validate CORS origins',72:'Validate credentialed CORS reads',73:'Validate CSRF state changes',74:'Validate open redirects',75:'Validate HPP/parser differences',76:'Validate SQL error differentials',77:'Validate arithmetic-only SSTI',78:'Validate CRLF header creation',79:'Validate traversal differentials',80:'Validate command interpretation candidate',81:'Validate OAST SSRF candidate',82:'Review signed URL binding',83:'Review upload processing',84:'Review custom-domain lifecycle',85:'Review cache key behavior',86:'Review canonical host influence',87:'Review realtime auth/channel matrix',88:'Review SAML RelayState/ACS binding',89:'Review recovery/session replay controls',90:'Require controlled impact proof',
91:'Stabilize baseline responses',92:'Use unique canaries',93:'Isolate one input per request',94:'Repeat with fresh canary',95:'Run counterfactual control',96:'Detect WAF/challenge pages',97:'Detect rate-limit artifacts',98:'Detect redirect artifacts',99:'Detect soft-404 behavior',100:'Detect non-HTML echo contexts',101:'Correlate native and external tools',102:'Apply cross-tool quorum',103:'Apply false-positive penalties',104:'Promote validated primitives',105:'Generate chain hypotheses',106:'Score chain priority',107:'Prove each chain arrow independently',108:'Gate request smuggling/desync',109:'Gate shared-cache poisoning',110:'Gate private-network/cloud SSRF',111:'Gate unrelated-user token access',112:'Gate destructive BOLA',113:'Gate DoS/resource exhaustion',114:'Record raw request/response evidence',115:'Record negative controls',116:'Record account/resource ownership',117:'Record cleanup proof',118:'Generate Markdown report',119:'Generate HTML report',120:'Generate JSON evidence ledger',121:'Generate chain graph',122:'Export machine-readable findings',123:'Summarize fingerprints',124:'Rank next actions',125:'Separate hypothesis from proof',126:'Separate priority score from CVSS',127:'Verify scope before every active phase',128:'Review program-specific exclusions',129:'Prepare report-ready reproduction',130:'Submit or keep digging decision'
}
def phase_for(n):return 1 if n<=20 else 2 if n<=45 else 3 if n<=90 else 4
STEP_CATALOG=[{'step':n,'id':f'STEP-{n:03d}','phase':phase_for(n),'phase_name':PHASES[phase_for(n)],'title':TITLES[n],'mode':'tool-assisted' if n<=20 or n in {37,38,39,71,74,76,77,78,79,81,91,92,96,97,98,99,100,101,102,103,118,119,120,123,124} else 'guided-manual'} for n in range(1,131)]
